name: tests

on:
  push:
    branches:
      - master
env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Deploy to Github Registry"
        run: mvn deploy -s settings.xml