name: tests

on:
  push:
    branches:
      - master
env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: chmod +x gradlew
      - name: "Deploy 'common' to Github Registry"
        run: ./gradlew --build-file=common/build.gradle build