name: tests

on:
  pull_request:
    branches:
      - master
env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Run tests"
        uses: ./.github/actions/tests
      - name: "Deploy to Github Registry"
        run: mvn deploy