name: tests

on:
  pull_request:
    branches:
      - master
env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Add permission to gradle"
        run: chmod +x gradlew
      - name: "Run tests"
        uses: ./.github/actions/tests